### ISSUE TITLE
Provide a convenient way to install (and use Kubernetes secrets)

### ISSUE THREAD

**Issue by collimarco** [logzio/logzio-k8s#18]
It would be useful to install logz.io and update its config with a simple command:

```
kubectl apply -f https://raw.githubusercontent.com/logzio/logzio-k8s/logzio-daemonset.yaml
```

The above command is very frequent and common - e.g. it is used by the Kubernetes dashboard and by other logging services.

Currently however we cannot use that simple command directly because you store the env variables inside the daemonset. This prevents the usage of the above command and it is also unsecure.

I suggest that you provide a file that can be used directly.

I also suggest that in the new file you use these env variables:

```
env:
- name: LOGZIO_TOKEN
  valueFrom:
    secretKeyRef:
      name: logzio-secrets
      key: logzio_token
- name: LOGZIO_URL
  valueFrom:
    secretKeyRef:
      name: logzio-secrets
      key: logzio_url
```
