### ISSUE TITLE
deprecated apis in k8s config

### ISSUE THREAD

**Issue by imnotashrimp** [logzio/logzio-k8s#42]
User left this on the logz-docs repo, but looks like it belongs here. 

Original issue: https://github.com/logzio/logz-docs/issues/332

### Describe the issue

Issue is described best here: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

### Recommended fix

Ran into this when trying to ship Kubernetes logs on the newest version. I had to make a couple small changes the logzio-daemonset.yml file to successfully ship.

Change `apiVersion: extensions/v1beta1` to `apiVersion: apps/v1`

and add the following object to spec:

```yaml
selector:
  matchLabels:
    k8s-app: fluentd-logzio
    version: v1
```
